config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :memberships
  resources :comments
  resources :posts

  resources :groups do
    collection do
      post :filter
    end
  end

  # Devise Routes
  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    unauthenticated :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
end

app/models/group.rb
class Group < ApplicationRecord
    # belongs_to :user
    has_many :posts

    has_many :memberships
    has_many :users, through: :memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def filter
    if params[:filter] == "all"
      @groups = Group.all
    elsif params[:filter] == "mine"
      @groups = Group.where(user_id: current_user.id)
    elsif params[:filter] == "joined"
      query = Membership.where(user_id: current_user.id)
      list = []
      query.each { |q| list.push(q.group_id) }
      @groups = Group.where(id: list)
    else
      @groups = []
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.update("groups", partial: "groups/filter_results", locals: {groups: @groups} )
        ]
      end
    end
  end

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @posts = Post.where(group_id: @group.id)

    @query = Membership.where(group_id: @group.id)
    list = []
    @query.each { |q| list.push(q.user_id) }
    @members = User.where(id: list)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    
    respond_to do |format|
      if @group.save
        Membership.create!(user_id: current_user.id, group_id: @group.id )
        format.html { redirect_to group_url(@group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:name, :user_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_filter_results.html.erb
<% groups.each do |group| %>
    <div id="<%= dom_id group %>" class="flex gap-5 my-7 place-items-center">

      <%# Group Details %>
      <div class="flex flex-col w-1/2 gap-2">
          <p class="text-lg font-bold"> <%= group.name %> </p>
          <div class="flex gap-5">
            
            <%# Logic for Member count %>
            <div>
              <% if Membership.where(group_id: group.id).count > 1 %> 
                <%= Membership.where(group_id: group.id).count %> Members
              <% else %>
                <%= Membership.where(group_id: group.id).count %> Member
              <% end %>
            </div>
            
            <%# Logic for Post count %>
            <div>
              <% if Post.where(group_id: group.id).count > 1 %> 
                <%= Post.where(group_id: group.id).count %> Posts
              <% else %>
                <%= Post.where(group_id: group.id).count %> Post
              <% end %>
            </div>

            <%# Logic for last activity %>
            <div>
            
              <%# Save date of latest reply %>
              <% if Reply.where(group_id: group.id).present? %>
                <% latest_reply = Reply.where(group_id: group.id).order(updated_at: :desc).first.updated_at.to_i %>
              <% else %>
                <% latest_reply = 0 %>
              <% end %>

              <%# Save date of latest comment %>
              <% if Comment.where(group_id: group.id).present? %>
                <% latest_comment = Comment.where(group_id: group.id).order(updated_at: :desc).first.updated_at.to_i %>
              <% else %>
                <% latest_comment = 0 %>
              <% end %>

              <%# Save date of latest post %>
              <% if Post.where(group_id: group.id).present? %>
                <% latest_post = Post.where(group_id: group.id).order(updated_at: :desc).first.updated_at.to_i %>
              <% else %>
                <% latest_post = 0 %>
              <% end %>

              <%# Display the latest date out of the 3 %>
              <% unless latest_reply == 0 && latest_comment == 0 && latest_post == 0 %>
                Latest activity <%= time_ago_in_words([latest_reply, latest_comment, latest_post].sort.last) %> ago
              <% end %>
            </div>
          </div>
      </div>

      <%# Join and Visit button logic %>
      <% if Membership.where(group_id: group.id).where(user_id: current_user.id).present? %>
        <%= link_to "Visit", group, class: "rounded-lg py-3 px-12 bg-slate-100 inline-block font-medium" %>
      <% else %>
        <%= form_with(model: Membership.new()) do |form|  %>
          <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
          <%= form.number_field :group_id, value: group.id, type: :hidden %>
          <%= form.submit "Join", class: "rounded-lg py-3 px-12 border-2 border-slate-500 inline-block font-medium"  %>
        <% end %>
      <% end %>

    </div>
<% end  %>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "contents") do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="flex gap5 my-5">

  <div >
    <p>
      <%= group.name %>
    </p>
    <div class="flex gap-5">
      <div>
        <% if Membership.where(group_id: group.id).count > 0 %> 
          <%= Membership.where(group_id: group.id).count %> Members
        <% else %>
          <%= Membership.where(group_id: group.id).count %> Member
        <% end %>
      </div>
      <div>
        <% if Post.where(group_id: group.id).count > 0 %> 
          <%= Membership.where(group_id: group.id).count %> Posts
        <% else %>
          <%= Membership.where(group_id: group.id).count %> Post
        <% end %>
      </div>
      <div>
        
        <% if Reply.where(group_id: group.id).present? %>
          <% latest_reply = Reply.where(group_id: group.id).order(updated_at: :desc).last.updated_at %>
        <% else %>
          <% latest_reply = 0 %>
        <% end %>

        <% if Comment.where(group_id: group.id).present? %>
          <% latest_comment = Comment.where(group_id: group.id).order(updated_at: :desc).last.updated_at %>
        <% else %>
          <% latest_comment = 0 %>
        <% end %>

        <% if Post.where(group_id: group.id).present? %>
          <% latest_post = Post.where(group_id: group.id).order(updated_at: :desc).last.updated_at %>
        <% else %>
          <% latest_post = 0 %>
        <% end %>

        <% unless latest_reply == 0 && latest_comment == 0 && latest_post == 0 %>
          Latest activity <%# time_ago_in_words([latest_reply,latest_comment, latest_post].sort.last) %> ago
        <% end %>

      </div>
    </div>
  </div>

  <div>
    <% if Membership.where(group_id: group.id).where(user_id: current_user.id).present? %>
      <%= link_to "Visit", group, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% else %>
      <%= form_with(model: Membership.new()) do |form|  %>
        <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
        <%= form.number_field :group_id, value: group.id, type: :hidden %>
        <%= form.submit "Join", class: "rounded-lg py-3 ml-2 px-5 bg-red-400 inline-block font-medium"  %>
      <% end %>
    <% end %>

    <%# if action_name != "show" %>
      <%# link_to 'Edit this group', edit_group_path(group), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <%# end %>
  </div>

</div>

app/views/groups/_group_posts.html.erb
<h2 class="text-3xl font-semibold mb-7"> All Posts </h2>

<% @posts.each do |post| %>
    <div id="post-<%= post.id %>">

        <h3 class="text-lg font-semibold"> <%= post.title %> </h3> <br/>
        <%= post.content %> <br/>

        <%# Statistics about the post %>
        <div class="flex gap-3 mt-3 text-slate-500">
            <%# Time of Last comment  %>
            <% if Comment.where(post_id: post.id).present? %>
                Last comment 
                <%= time_ago_in_words(Comment.where(post_id: post.id).order(updated_at: :desc).last.updated_at) %>
                ago  •  
            <% end %>

            <%# Edit link %>
            <% if current_user.id == post.user_id %>
                <%= link_to 'Edit', edit_post_path(post) %>  •      
            <% end %>

            <%# Delete link %>
            <% if current_user.id == post.user_id || current_user.id == @group.user_id %>
                <div class="flex gap-3">
                    <%= form_with(model: post, method: :delete) do |form| %>
                        <%= form.submit "Delete" %>
                    <% end %>
                    <span> • </span>
                </div>
            <% end %>

            <%# Created by %>
            Created by 
            <% if current_user.id == post.user_id %>
                You
            <% else %>
                <%= User.where(id: post.user_id).first.name %>
            <% end %>

        </div>
        <%= link_to "View post ->", post %>
    </div>
    <br/> <br/> <br/>
<% end %>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>

  <%= link_to "Show this group", @group, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to groups", groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/index.html.erb
<div class="w-full">  
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Groups</h1> <br/>

  <div class="flex justify-between items-center">

    <%# Filters for the group %>
    <div class="border-2 border-gray-600 flex px-4 py-2 w-fit rounded-lg gap-2">
      <%= render(FilterComponent.new()) %>
    </div>

    <%# Modal Elements %>
    <div data-controller="modal">

      <%# Button to trigger modal %>
      <button data-action="click->modal#toggle" class="rounded-lg py-3 px-5 bg-green-500 text-white block font-medium">
        New Group
      </button>

      <%# Modal itself %>
      <div data-modal-target="modalArea" hidden>
        <%= render(ModalComponent.new('Create', current_user.id, Group.new(), 'Create' )) %>
      </div>
    </div>

  </div>

  <%# List of Groups %>
  <div id="groups" class="min-w-full">
    <%= render "groups/filter_results", groups: @groups %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New group</h1>

  <%= render "form", group: @group %>

  <%= link_to 'Back to groups', groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/groups/show.html.erb
<div class="flex gap-5">
  
  <%# Start of left column %>
  <div class="mx-auto w-10/12 flex flex-col">
    
    <%# Top row %>
    <div>
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>

      <div data-controller="modal" class="flex gap-7">
        <h1 class="text-3xl font-bold"><%= @group.name %></h1>
        <div data-action="click->modal#toggle"> <i class="fa-solid fa-gear text-3xl text-slate-500"></i> </div>

        <%# Modal %>
        <div data-modal-target="modalArea" hidden>
          <%= render(ModalComponent.new('Edit', current_user.id, @group, 'Save' )) %>
        </div>
      </div>
    </div>


    <%# Form to create new Post %>
    <div>
      <%= form_with(model: Post.new()) do |form| %>

        <div class="my-5">
          <%= form.text_field :title, placeholder: "What's the title of this post?", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>

        <div class="my-5">
          <%= form.text_area :content, rows: 4, placeholder: "Write your post...", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>

        <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
        <%= form.number_field :group_id, value: @group.id, type: :hidden %>

        <div class="flex justify-end">
          <%= form.submit class: "rounded-lg py-3 px-5 bg-green-500 text-white inline-block font-medium cursor-pointer" %>
        </div>
      <% end %>
    </div>

    <%# View all posts %>
    <div> <%= render "group_posts" %> </div>
  </div>

  <%# Start of Members column %>
  <div class="w-2/12">
    <h2 class="text-lg font-semibold mb-3"> Members </h2>
    
    <%# Generate name and delete button for each member %>
    <% @members.each do |member|%>
      <div class="flex justify-between pr-5 py-3">
        <p> <%= member.name %> </p>
        <div>
          <% if current_user.id == member.id || current_user.id == @group.user_id %>
            <%= form_with(model: Membership.find(@query.where(user_id: member.id).first.id), method: :delete) do |form| %>
              <div data-controller="membership">
                <i class="fa-solid fa-xmark" data-action="click->membership#delete"></i>
                <%= form.submit hidden: true, data: { membership_target: "submit" } %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>

  </div>
  
</div>